import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MockUserProvider from "@/components/global/MockUserProvider";
import { NotificacionesProvider } from "@/context/NotificacionesContext";
import { SessionManagerProvider } from "@/context/SessionManagerContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Solcial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionManagerProvider>
        <NotificacionesProvider>
          <MockUserProvider>
            {children}
          </MockUserProvider>
        </NotificacionesProvider>
        </SessionManagerProvider>
      </body>
    </html>
  );
}