// MODIFICAR: c:\Users\Lian Li\Desktop\FrontEnd_Solcial\solcial\src\app\layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "@/components/ClientProviders"; // ✅ IMPORT CLIENT WRAPPER
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Solcial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Ici, tu peux choisir la langue dynamiquement (ex: depuis le localStorage, cookie, etc.)
  const locale = "en"; // ou "fr", à rendre dynamique plus tard

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ✅ USAR CLIENT WRAPPER */}
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}